image: "ruby:2.5.1"

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor

rspec:
  stage: test
  script:
    - rspec
  artifacts:
    paths:
      - coverage/

rubocop:
  script:
    - bundle exec rubocop

pages:
  stage: deploy
  dependencies:
    - rspec
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master