plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - bin/**/*
    - vendor/**/*

Layout/LineLength:
  Max: 100

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "**/*_spec.rb"

Lint/EmptyClass:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Max: 15
