AllCops:
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - vendor/**/*
  TargetRubyVersion: 2.5.1

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - '**/*_spec.rb'
