---
version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: '720c03bcc2eb17a5494a1e4bc18dfd0044b7a9819e0299f271278fd9a3da613f'
    working_directory: ~/selfies
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: selfies-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: selfies-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # Run the tests
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec
            ./cc-test-reporter after-build --exit-code $?

      # Enforce better practices
      - run: bundle exec rubocop

      - store_test_results:
          path: coverage
